#!/bin/sh

print_help() {
cat <<EOF
Usage: notmuch-autocrypt-lookup PEER-ADDRESS

EOF
}
if test "$1" = -h || test "$1" = --help; then
    print_help
    exit 0
elif ! test "$#" = 1; then
    print_help >&2
    exit 1
fi

notmuch search \
        --output=files \
        --sort=newest-first \
        --limit=100 \
        from:"$1" |
    xargs awk \
        'BEGIN { output=0 };
         /^Autocrypt:/ { print; output=1; next };
         output==1 && /^[ \t]/ { print };
         output==1 && /^[^ \t]/ { exit };' |
    tr -d '\n \t' |
    grep "^Autocrypt:addr=$1;" |
    sed 's,^.*keydata=,,' |
    base64 -d |
    gpg --import
